4 TO - DO - Task
Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
# 1. Initialize an empty array with size 2X2.

import numpy as np

arr=np.empty((2,2))
print(arr)

[[1.20953847e-315 0.00000000e+000]
 [6.89820968e-310 5.78153247e-317]]


In [2]:
# 2. Initialize an all one array with size 4X2.

arr=np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

arr=np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [4]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

arr=np.zeros_like(arr)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

arr=np.ones_like(arr)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
#6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

new_list=[1,2,3,4]
arr=np.array(new_list)
print(arr)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [7]:
#1.Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()

matrix=np.arange(0,9)
matrix=matrix.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#3.Create a 3X3 identity matrix.{Hint:np.eye()}

matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}

arr=np.random.randint(0,100,size=30)
mean=arr.mean()
print(arr)
print("Mean: ",mean)

[ 5 76 94 69  0 22 56 59 78 50 24 67 97 76 74 87 92 52  9 90 84 84 54 63
 53 46 89 77 31 67]
Mean:  60.833333333333336


In [11]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.

arr = np.random.randint(0,100,size=(10,10))
min = arr.min()
max = arr.max()
print(arr)
print(f"Min value:{min}")
print(f"Max value:{max}")

[[38 89 27 84 24 29 72 95 91 23]
 [18 18  7 47 81 76 22 87 89 10]
 [49 74 62 69 70 18 96 26 12 76]
 [98 89 96 68 73 58 17 83 61 23]
 [37 26 61 57 42  4 21 97 95 77]
 [58 25  0 51 30  1 85 92 26 31]
 [36 49 63 49 43  0 38  3 77 99]
 [28  7 33 12 47 24 86 88 98 29]
 [96 47 25 36 54 61 25  7 96 32]
 [12 89 56 44 59 53 85 37 96 80]]
Min value:0
Max value:99


In [12]:
#6. Create a zero array of size 10 and replace 5th element with 1.

arr=np.zeros(10)
print(arr)
arr[4]=1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
#7. Reverse an array arr = [1,2,0,0,4,0].

arr=[1,2,0,0,4,0]
print(arr)
arr = arr[::-1]
print(arr)

[1, 2, 0, 0, 4, 0]
[0, 4, 0, 0, 2, 1]


In [14]:
#8. Create a 2d array with 1 on border and 0 inside.

arr=np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

matrix=np.zeros((8,8))
matrix[1::2,::2]=1
matrix[::2,1::2]=1
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [16]:
#1. Add the two array.

x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]]);
v=np.array([9,10])
w=np.array([11,12]);

print(x)
print(y)
print(w)
print(v)
print(np.add(x,y))
print(np.add(w,v))

[[1 2]
 [3 5]]
[[5 6]
 [7 8]]
[11 12]
[ 9 10]
[[ 6  8]
 [10 13]]
[20 22]


In [17]:
#2. Subtract the two array.

print(np.subtract(x,y))
print(np.subtract(w,v))

[[-4 -4]
 [-4 -3]]
[2 2]


In [18]:
#3. Multiply the array with any integers of your choice.

print(x*10)
print(y*2)
print(v*6)
print(w*4)

[[10 20]
 [30 50]]
[[10 12]
 [14 16]]
[54 60]
[44 48]


In [19]:
#4.Find the square of each element of the array.

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Square each element
x_squared = np.square(x)
y_squared = np.square(y)
v_squared = np.square(v)
w_squared = np.square(w)

print("x squared:\n", x_squared)
print("y squared:\n", y_squared)
print("v squared:\n", v_squared)
print("w squared:\n", w_squared)

x squared:
 [[ 1  4]
 [ 9 25]]
y squared:
 [[25 36]
 [49 64]]
v squared:
 [ 81 100]
w squared:
 [121 144]


In [20]:
#5.Find the dot product between: v(and)w ; x(and)v ; x(and)y.

print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

219
[29 77]
[[19 22]
 [50 58]]


In [21]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.

print(np.concatenate((x,y)))
print(np.vstack((v,w)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [22]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

print(np.concatenate((x,v)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [23]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 =\n", I)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [24]:

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [25]:
# 3. Prove (AB)^T = B^T A^T
lhs = np.transpose(AB)
rhs = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T =\n", lhs)
print("B^T A^T =\n", rhs)

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]


In [26]:
#• Solve the following system of Linear equation using Inverse Methods.

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


In [27]:
import numpy as np
import time

4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [28]:
#1. Element-wise Addition

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
end = time.time()

print("Python list addition time:", end - start, "seconds")

Python list addition time: 0.0669248104095459 seconds


In [29]:
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start = time.time()
result_np = arr1 + arr2
end = time.time()

print("NumPy array addition time:", end - start, "seconds")

NumPy array addition time: 0.002042531967163086 seconds


In [30]:
#2. Element-wise Multiplication

start = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
end = time.time()

print("Python list multiplication time:", end - start, "seconds")

Python list multiplication time: 0.06832385063171387 seconds


In [31]:
start = time.time()
result_np = arr1 * arr2
end = time.time()

print("NumPy array multiplication time:", end - start, "seconds")

NumPy array multiplication time: 0.0027685165405273438 seconds


In [32]:
#3. Dot Product

start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()

print("Python list dot product time:", end - start, "seconds")

Python list dot product time: 0.06218600273132324 seconds


In [33]:
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()

print("NumPy dot product time:", end - start, "seconds")

NumPy dot product time: 0.0017743110656738281 seconds


In [34]:
#4. Matrix Multiplication (1000 × 1000)

# Create two 1000x1000 matrices using lists
matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

start = time.time()
result_matrix = [[sum(a*b for a, b in zip(row, col))
                  for col in zip(*matrix2)]
                  for row in matrix1]
end = time.time()

print("Python list matrix multiplication time:", end - start, "seconds")

Python list matrix multiplication time: 80.59270882606506 seconds


In [35]:
mat1 = np.random.rand(1000, 1000)
mat2 = np.random.rand(1000, 1000)

start = time.time()
result_np = np.dot(mat1, mat2)   # or mat1 @ mat2
end = time.time()

print("NumPy matrix multiplication time:", end - start, "seconds")

NumPy matrix multiplication time: 0.04693174362182617 seconds
